'use strict';
const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const { randomUUID } = require('node:crypto');
const mysql = require('mysql2/promise');
const { inventory, buildTriggers, assertSchema } = require('../src/services/audit/schema');
// Explicit disposable local DB only. Never reads the application's .env.
const socketPath = process.env.AUDIT_TEST_MYSQL_SOCKET;
test('real InnoDB triggers, rollback, delete retention and connection isolation', { skip: !socketPath }, async t => {
  assert.ok(path.isAbsolute(socketPath), 'Use an explicit local test socket');
  const database = 'audit_test_' + randomUUID().replaceAll('-', '');
  const db = await mysql.createConnection({ socketPath, user: 'root', multipleStatements: true });
  t.after(async () => { await db.query(`DROP DATABASE IF EXISTS \`${database}\``); await db.end(); });
  await db.query(`CREATE DATABASE \`${database}\`; USE \`${database}\``);
  await db.query(fs.readFileSync(path.join(__dirname, '../../Database/migrations/058_admin_audit.sql'), 'utf8'));
  await db.query(`CREATE TABLE products (id INT PRIMARY KEY AUTO_INCREMENT, owner_user_id CHAR(36), name VARCHAR(80), price INT, password_hash VARCHAR(80), phone VARCHAR(80)) ENGINE=InnoDB;
    CREATE TABLE course_products (id INT PRIMARY KEY, owner_user_id CHAR(36), price INT) ENGINE=InnoDB;
    CREATE TABLE course_orders (id INT PRIMARY KEY, product_id INT, total_amount INT) ENGINE=InnoDB`);
  const tables = await inventory(db);
  for (const [table, columns] of tables) for (const trigger of buildTriggers(table, columns, tables)) await db.query(trigger.sql);
  await assertSchema(db);
  const [request] = await db.query("INSERT INTO admin_audit_requests(request_id,module,action,method,route) VALUES(?, 'products','create','POST','/admin/products')", [randomUUID()]);
  await db.query('SET @leader_audit_request=?', [request.insertId]);
  await db.beginTransaction();
  const [product] = await db.query("INSERT INTO products(owner_user_id,name,price,password_hash,phone) VALUES('owner','Test',10,'secret','private')");
  assert.equal(product.insertId, 1, 'trigger LAST_INSERT_ID must not replace business ID');
  await db.query('UPDATE products SET price=20 WHERE id=1');
  await db.commit();
  const [changes] = await db.query('SELECT * FROM admin_audit_changes ORDER BY id');
  assert.equal(changes.length, 2); assert.ok(!JSON.stringify(changes).includes('secret')); assert.ok(!JSON.stringify(changes).includes('private'));
  const after = typeof changes[1].after_json === 'string' ? JSON.parse(changes[1].after_json) : changes[1].after_json;
  assert.equal(after.price, 20);
  await db.beginTransaction(); await db.query('UPDATE products SET price=30 WHERE id=1'); await db.rollback();
  const [[count]] = await db.query('SELECT COUNT(*) n FROM admin_audit_changes'); assert.equal(count.n, 2);
  await db.query('SET @leader_audit_request=NULL'); await db.query('UPDATE products SET price=40 WHERE id=1');
  const [[outside]] = await db.query('SELECT COUNT(*) n FROM admin_audit_changes'); assert.equal(outside.n, 2);
  await db.query('SET @leader_audit_request=?', [request.insertId]);
  await db.query("INSERT INTO course_products VALUES(1,'tenant-a',100)");
  await db.query('INSERT INTO course_orders VALUES(1,1,100)');
  const [[scope]] = await db.query("SELECT s.after_scope FROM admin_audit_scopes s JOIN admin_audit_changes c ON c.id=s.change_id WHERE c.resource_table='course_orders'");
  const parsed = typeof scope.after_scope === 'string' ? JSON.parse(scope.after_scope) : scope.after_scope;
  assert.equal(parsed.resolved_owner_id, 'tenant-a');
  await db.query('DELETE FROM products WHERE id=1');
  const [[deleted]] = await db.query("SELECT COUNT(*) n FROM admin_audit_changes WHERE resource_table='products'"); assert.equal(deleted.n, 3);
  // Fault injection into the audit sink must reject the actual business mutation.
  await db.query("CREATE TRIGGER audit_test_fail BEFORE INSERT ON admin_audit_changes FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='injected failure'");
  await assert.rejects(db.query('UPDATE course_products SET price=999 WHERE id=1'), /AUDIT_LOG_UNAVAILABLE/);
  const [[unchanged]] = await db.query('SELECT price FROM course_products WHERE id=1'); assert.equal(unchanged.price, 100);
});
